"use client";

import React, { useState, useRef } from "react";
import { Copy, Check } from "lucide-react";

interface CodeBlockProps {
  children?: React.ReactNode;
}

const CodeBlock = ({ children, ...props }: CodeBlockProps) => {
  const [copied, setCopied] = useState(false);
  const preRef = useRef<HTMLPreElement>(null);

  const handleCopy = () => {
    if (!preRef.current) return;
    // Extract raw text, omitting HTML tags generated by the syntax highlighter
    const codeText = preRef.current.textContent || "";
    navigator.clipboard.writeText(codeText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative group my-6 rounded-lg overflow-hidden border border-black/10 dark:border-white/5 bg-black/40">
      {/* Code Header Bar */}
      <div className="flex items-center justify-between px-4 py-2 bg-black/30 text-[10px] font-mono text-muted-foreground select-none">
        <span>source-code</span>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 hover:text-white transition-colors cursor-pointer"
        >
          {copied ? (
            <>
              <Check className="h-3 w-3 text-green-500" />
              <span>Copied!</span>
            </>
          ) : (
            <>
              <Copy className="h-3 w-3" />
              <span>Copy</span>
            </>
          )}
        </button>
      </div>
      {/* Code Area */}
      <pre
        ref={preRef}
        className="p-4 overflow-x-auto no-scrollbar font-mono text-xs text-white/90 leading-relaxed"
        {...props}
      >
        {children}
      </pre>
    </div>
  );
};

// Map headings to clean slugs for anchor linkages
function createSlug(node: React.ReactNode): string {
  const text = String(node);
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim();
}

export const mdxComponents = {
  h1: ({ children, ...props }: React.ComponentPropsWithoutRef<"h1">) => {
    const id = createSlug(children);
    return (
      <h1 id={id} className="text-3xl font-extrabold mt-10 mb-6 scroll-mt-24 text-foreground" {...props}>
        {children}
      </h1>
    );
  },
  h2: ({ children, ...props }: React.ComponentPropsWithoutRef<"h2">) => {
    const id = createSlug(children);
    return (
      <h2 id={id} className="text-2xl font-bold mt-8 mb-4 border-b border-black/10 dark:border-white/5 pb-2 scroll-mt-24 text-foreground" {...props}>
        {children}
      </h2>
    );
  },
  h3: ({ children, ...props }: React.ComponentPropsWithoutRef<"h3">) => {
    const id = createSlug(children);
    return (
      <h3 id={id} className="text-xl font-bold mt-6 mb-3 scroll-mt-24 text-foreground" {...props}>
        {children}
      </h3>
    );
  },
  pre: (props: React.ComponentPropsWithoutRef<"pre">) => <CodeBlock {...props} />,
};
